name: Test Hit
on:
  workflow_run:
    workflows: [Test Miss]
    types:
      - completed
jobs:
  Cache-Hit:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        skip-save: [true, false]
      fail-fast: false
    steps:
      - id: check-run
        uses: LouisBrunner/checks-action@69aaabbcf32668b60dc03b65deabfe23e92d9c41 # v1.6.0
        with:
          token: ${{ github.token }}
          name: Cache Hit / ${{ matrix.os }} / ${{ matrix.skip-save }}
          status: in_progress
          repo: ${{ github.event.workflow_run.head_repository.full_name }}
          sha: ${{ github.event.workflow_run.head_commit.id }}
          details_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      - uses: actions/checkout@v3
        with:
          path: rust-sccache-action
      - name: Installing Rust
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          toolchain: stable
      - uses: ./rust-sccache-action
        id: cache
        with:
          key: ${{ github.event.workflow_run.id }}
          skip-save: ${{ matrix.skip-save }}
      - run: mkdir target
      - env:
          CACHE_HIT: ${{ steps.cache.outputs.cache-hit }}
        run: |
          if [[ "$CACHE_HIT" != 'true' ]]; then
            echo 'Cache was missed, but it should not have been.'
            exit 1
          fi
      - if: always()
        uses: LouisBrunner/checks-action@69aaabbcf32668b60dc03b65deabfe23e92d9c41 # v1.6.0
        with:
          token: ${{ github.token }}
          check_id: ${{ steps.check-run.outputs.check_id }}
          conclusion: ${{ job.status }}
          repo: ${{ github.event.workflow_run.head_repository.full_name }}
          sha: ${{ github.event.workflow_run.head_commit.id }}
          details_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
